-- Lua 5.1 + the globals this addon calls.
-- Undefined globals and syntax errors still fail.
-- Unused locals, shadowing, and line length do not: the shipped files
-- have over a hundred of each, and silencing code 113 would hide typos.
std = "lua51"
max_line_length = false
codes = true
ignore = {
    "212/self",
    "421",
    "431",
    "512",
    "311",
    "211",
    "213",
}
globals = {
    "LooseButtonsLogic",
    "LooseButtonsDB",
    "BINDING_HEADER_LOOSEBUTTONS",
    "BINDING_HEADER_LOOSEBUTTONSLAUNCHERS",
    "SLASH_LOOSEBUTTONS1",
    "SLASH_LOOSEBUTTONS2",
    "StaticPopupDialogs",
    "SlashCmdList",
}
read_globals = {
    "ACCEPT",
    "CANCEL",
    "C_AddOns",
    "C_Container",
    "C_EncodingUtil",
    "C_Item",
    "C_Spell",
    "C_SpellBook",
    "C_Timer",
    "ClearCursor",
    "ClearOverrideBindings",
    "CreateFrame",
    "Enum",
    "EventUtil",
    "GameMenuFrame",
    "GameTooltip",
    "GameTooltip_AddHighlightLine",
    "GetBindingIndex",
    "GetBindingKey",
    "GetBindingName",
    "GetBindingText",
    "GetCurrentBindingSet",
    "GetCursorPosition",
    "GetItemCount",
    "GetMacroInfo",
    "GetMouseFoci",
    "GetRealmName",
    "InCombatLockdown",
    "IsAltKeyDown",
    "IsControlKeyDown",
    "IsShiftKeyDown",
    "KeybindFrames_InQuickKeybindMode",
    "MenuUtil",
    "MinimalSliderWithSteppersMixin",
    "NO",
    "PickupMacro",
    "PlaceAction",
    "PlayerSpellsFrame",
    "QuickKeybindFrame",
    "QuickKeybindTooltip",
    "SPELLBOOK_FONT_COLOR",
    "SaveBindings",
    "ScrollUtil",
    "SecureHandlerWrapScript",
    "SetBinding",
    "SetOverrideBinding",
    "SetOverrideBindingClick",
    "SetPortraitTexture",
    "StaticPopup_Hide",
    "StaticPopup_Show",
    "ToggleLegacySystemUI",
    "UIParent",
    "UnitClass",
    "UnitName",
    "YES",
    "hooksecurefunc",
    "issecretvalue",
    "securecall",
}
